import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import { PageHeading } from "./components/PageHeading";
import { FavoritesProvider } from "@/src/app/contexts/FavoritesContext";

import "./globals.css";

const notoSans = Noto_Sans({
	weight: ["400", "600"],
	subsets: ["cyrillic-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.className} antialiased`}
      >
        <FavoritesProvider>
          <div className="flex flex-col min-h-screen">
            <PageHeading />
            {children}
          </div>
        </FavoritesProvider>
      </body>
    </html>
  );
}
